### ISSUE TITLE
Erreur JS

### ISSUE THREAD

**Issue by foucdeg** [kraynel/silaexpert#4]
J'ai eu l'erreur suivante en essayant d'utiliser l'outil pour la première fois:

```
$ sila-cli -u foucauldd -p password -l
Generating client keys
Loading request templates
fs.js:584
  return binding.open(pathModule._makeLong(path), stringToFlags(flags), mode);
                 ^

Error: ENOENT: no such file or directory, open 'soap/loginRequest.xml'
    at Error (native)
    at Object.fs.openSync (fs.js:584:18)
    at Object.fs.readFileSync (fs.js:431:33)
    at init (/usr/local/lib/node_modules/sila-cli/client.js:24:40)
    at Object.execute (/usr/local/lib/node_modules/sila-cli/client.js:32:3)
    at Object.<anonymous> (/usr/local/lib/node_modules/sila-cli/index.js:25:8)
    at Module._compile (module.js:397:26)
    at Object.Module._extensions..js (module.js:404:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Function.Module.runMain (module.js:429:10)
    at startup (node.js:139:18)
    at node.js:999:3
```

**Comment by kraynel** [comment]
Il n'arrive pas à lire les templates de requêtes qui sont censés être dans `/usr/local/lib/node_modules/sila-cli/soap/` d'après le log. Tu peux vérifier qu'il a bien tout récupéré dans ce répertoire ?

Sinon, tu peux essayer d'aller directement dans `/usr/local/lib/node_modules/sila-cli` et lancer un `node index.js -u foucauldd -p XXX -l`.

Dernière piste, tu as dû faire un sudo pour faire l'installation globale, peut-être que les droits ne sont pas bien positionnés sur tous les fichiers. Perso, j'utilise [nvm](https://github.com/creationix/nvm) pour gérer mes version de node, ça permet notamment de faire des `npm install -g` sans avoir besoin de sudo.

**Comment by foucdeg** [comment]
Les templates sont là avec des droits en lecture pour tout le monde.

Erreur en suivant ta suggestion : 

```
$ node index.js -u foucauldd -p password -l
Generating client keys
Loading request templates
Sending login request
RSA key exchange ok, got id 26017
Unhandled rejection TypeError: Cannot read property 'ID_PAISALARIE' of null
    at /usr/local/lib/node_modules/sila-cli/client.js:59:28
    at tryCatcher (/usr/local/lib/node_modules/sila-cli/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/usr/local/lib/node_modules/sila-cli/node_modules/bluebird/js/release/promise.js:504:31)
    at Promise._settlePromise (/usr/local/lib/node_modules/sila-cli/node_modules/bluebird/js/release/promise.js:561:18)
    at Promise._settlePromise0 (/usr/local/lib/node_modules/sila-cli/node_modules/bluebird/js/release/promise.js:606:10)
    at Promise._settlePromises (/usr/local/lib/node_modules/sila-cli/node_modules/bluebird/js/release/promise.js:685:18)
    at Async._drainQueue (/usr/local/lib/node_modules/sila-cli/node_modules/bluebird/js/release/async.js:138:16)
    at Async._drainQueues (/usr/local/lib/node_modules/sila-cli/node_modules/bluebird/js/release/async.js:148:10)
    at Immediate.Async.drainQueues [as _onImmediate] (/usr/local/lib/node_modules/sila-cli/node_modules/bluebird/js/release/async.js:17:14)
    at processImmediate [as _immediateCallback] (timers.js:383:17)
```

**Comment by foucdeg** [comment]
@kraynel dans client.js ligne 49 tu attends une clé `ONG0` ou `ONG1` dans `result.value.$R.value`, mais moi j'ai ça : 

``` javascript
{
  SIGM: { type: 12, value: '' },
  DLP: { type: 2, value: false },
  NS: { type: 5, value: 1 },
  IDENT: { type: 5, value: 2 },
  NOMC: { type: 12, value: '' },
  BALC: { type: 2, value: false },
  NOMD: { type: 12, value: '' },
  NBMID: { type: 5, value: 0 },
  NOMG: { type: 12, value: '' },
  NOME: { type: 12, value: '' },
  NCS: { type: 5, value: 0 },
  NAT: { type: 5, value: 0 },
  NLANG: { type: 12, value: '' },
  COLDD: { type: 12, value: '' },
  COLBA: { type: 2, value: false },
  CLANG: { type: 5, value: 0 }
}
```

**Comment by kraynel** [comment]
Hum étrange. Il faudrait que j'aille creuser dans le code .NET du client pour avoir un truc propre. Le cas ONG0/ONG1 à l'air d'être lié à la société de rattachement, tu es bien Theodo/Theodo Academy ?

Sinon je peux passer te voir, on peut regarder le contenu de `result.value` ensemble et essayer de trouver la bonne clé.

**Comment by foucdeg** [comment]
Oui je suis Academy normalement.
Je suis à la Défense malheureusement ... faudrait qu'on se cale un moment quand je suis là.

**Comment by foucdeg** [comment]
euh je suis trop con, t'es là aussi -_-
bref, quand tu veux.

**Comment by kraynel** [comment]
Après vérif de mon côté, ça me fait la même erreur, et en y allant avec un Internet Explorer, je n'ai plus accès aux fiches de paies. 

J'ai reçu un mail le 05/07 de Silae qui me disait "Un collaborateur vient de rajouter à votre compte utilisateur l'accès au portail salarié.", ils ont peut-être changé les droits à ce moment.

**Comment by kraynel** [comment]
Je leur ai envoyé un mail, on verra leur réponse.

**Comment by florentdestremau** [comment]
@kraynel j'ai ce bug aussi, ça veut dire que toutes les fiches de paies sont bloquées en ce moment ?

**Comment by foucdeg** [comment]
@florentdestremau Y'a toujours la VM avec IE

**Comment by florentdestremau** [comment]
ah chiant ^^

**Comment by kraynel** [comment]
Récap : 
J'ai eu le même bug la semaine dernière.
Même l'accès depuis la VM était mort, je pouvais me logger mais plus d'accès à la partie perso avec les congés/paies. Un petit mail à paies@experts-entreprendre.com et j'avais de nouveau accès, VM + cli... 

Ils n'ont pas l'air de tout bien maîtriser...

Il faut que je rajoute des logs pour le debug, je vais essayer de faire ça.

Edit : pareil chez moi aujourd'hui, je pense que le soucis est de leur côté.

**Comment by florentdestremau** [comment]
J'ai essayé sur mon IE sous windows, j'arrive à me connecter mais j'ai pas d'accès à la partie perso. Mail envoyé à paies@experts-entreprendre.com et j'attends de leurs nouvelles.

**Comment by florentdestremau** [comment]
![image](https://cloud.githubusercontent.com/assets/2852204/17204219/8dff82be-54a4-11e6-9ad2-1e0851c3dc19.png)

Ok ouais ils galèrent haha
